#!/bin/sh
## Copyright (c) 2024-2025 by mobinmob  <mobinmob@disroot.org
##This program is free software: you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free 
## Software Foundation, version 2.0 of the License.
## This program is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along with
## this program. If not, see <https://www.gnu.org/licenses/>.
### SPDX short identifier: GPL-2.0-only

#setting default configuration
readonly default_repo=https://github.com/void-linux/void-packages.git
readonly repo_abyss_packages=https://codeberg.org/mobinmob/abyss-packages.git
default_repo_dir=$(printf '%s' "$default_repo" | awk -F"/" '{ print "/"$(NF-1)"/"$NF }'| tr "/" "_")
readonly default_repo_dir
conf_workdir="${HOME}/.xut"
#colours
green=$(tput setaf 2)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
reset_colour=$(tput sgr0)
#define a log filename
conf_log_dir="$conf_workdir/logs"
log_file="$conf_log_dir/$(basename "$0")_$(date +"%Y%m%d_%T")".log
readonly log_file
#set default operation variables
op_log=0
op_xbps_src=

msg() {
	if [ "${1}" = "error" ]; then printf "(!!) Error: %40s\n" "${red} $* ${reset_colour}" && exit 1 
	elif [ "${1}" = "warn" ]; then printf "(~~) Warning: %40s\n" "${yellow} $* ${reset_colour}"
	elif [ "${1}" = "info" ]; then printf "(~>) Info: %40s\n" "${green} $* ${reset_colour}"
	 fi
}

usage() {
	cat <<-EOH
	Usage: $(basename "$0") [options]

	*x*tra *u*ser *t*emplates
	Build and install packages for Void Linux, from the abyss-packages unofficial repo
	
	OPTIONS
	 -i	<package1,package2>	Build and install a list of (comma-seperated) packages.
	 -l	Keep a log file under $conf_log_dir.
	 -x	Give xbps-src commands.
	 -s	Sync the repos.
	 -h	Display this usage information.
	EOH
}

retrieve_repos() {
	repos_list="$default_repo $repo_abyss_packages"
	for i in $repos_list; do 
	repodir=$(printf '%s' "$i" | awk -F"/" '{ print "/"$(NF-1)"/"$NF }'| tr "/" "_")
	if [ ! -d "$conf_workdir"/"$repodir" ]; then
		msg info Cloning "$i"...
		git clone --depth 1  "$i" "$conf_workdir"/"$repodir" || msg error Cannot clone "$i" repo.
		msg info Succesfully cloned "$i"!
	else msg warn "$i" already exist in "$repodir"! ;fi
	done
} 
sync_repos() {
	repos_list="$default_repo $repo_abyss_packages"
	for i in $repos_list; do 
	repodir=$(printf '%s' "$i" | awk -F"/" '{ print "/"$(NF-1)"/"$NF }'| tr "/" "_")
	msg info  Syncing with "$i"...
	cd "$conf_workdir"/"$repodir" || msg error Cannot change to the "$conf_workdir"/"$repodir"!
	git pull "$i" "$(git branch --show-current)" || msg error Cannot sync to the "$i".
	msg info Succesfully synced  "$i" repo!
	done
}

integrate_xtra_templates() {
	cp -r "$conf_workdir"/_mobinmob_abyss-packages.git/* "$conf_workdir"/"$default_repo_dir"/srcpkgs/ || msg error Cannot copy templates...
}

xbps_src_command() {
	cd "$conf_workdir"/"$default_repo_dir" - && ./xbps-src "$op_xbps_src"
}

install_packages() {
	package_list="$(echo "$packages" | tr ',' ' ')"
	export package_list="$package_list"
	[ -z "$package_list" ] && error Nothing to do...
	for i in $package_list; do 
		cd "$conf_workdir"/"$default_repo_dir" -  && ./xbps-src pkg "$i"
	done
	# shellcheck disable=SC2086
	xi $package_list
}

main() {
#program execution starts here
# Check for root
[ "$(id -u)" -eq 0 ] && msg error Please run the program as a user!
msg info Full comand given is [xut "$showargs"].
#Get the configuration from the conf file if it exists.
# shellcheck disable=SC1091
if [ -e "$XDG_CONFIG_HOME"/.xutconf ]; then
	. "$XDG_CONFIG_HOME"/.xutconf
	msg info Using configuration from "$XDG_CONFIG_HOME"/.xutconf.
elif [ -e "$HOME"/.xutconf ]; then
	. "$HOME"/.xutconf
	msg info Using configuration from "$HOME"/.xutconf.
else msg warn Using the default configuration.
fi
# Check for needed dirs.
[ ! -e "$conf_workdir/logs" ] && mkdir -pv "$conf_workdir/logs" 
# clean or zap repos before other ops
[ -n "$op_xbps_src" ] && xbps_src_command
# Clone repos if needed 
retrieve_repos
[ "$op_sync" = 1 ] && sync_repos
#Enable building restricted packages
if grep -q "XBPS_ALLOW_RESTRICTED=yes" "$conf_workdir"/"$default_repo_dir"/etc/conf ; then
	msg info Building restricted packages is enabled!
else printf "%s" "XBPS_ALLOW_RESTRICTED=yes" "\n" >> "$conf_workdir"/"$default_repo_dir"/etc/conf;
fi
#Boostrap if masterdir is not populated
if [ ! -e "$conf_workdir"/"$default_repo_dir"/masterdir-"$(xbps-uhelper arch)"/usr/bin/xbps-install ];
then  op_xbps_src="binary-bootstrap" && xbps_src_command; fi
#all template dirs are copied 
integrate_xtra_templates
[ -n "$packages" ] && install_packages
}
#Keep only 5 log files, including the current one.
find "$conf_log_dir" -name "xut_*.log" -print | tail -n+5 | xargs rm -f

while getopts "si:hlx:" OPTION; do
	case "${OPTION}" in
		s) op_sync=1;;
		i) packages="$OPTARG";;
		l) op_log=1;;
		x) op_xbps_src="$OPTARG";;
		h) usage ; exit 0;;
		*) usage ; exit 0;;
	esac
done
# Capture all the arguments given
showargs="$(printf "%s" "$*")"
shift $((OPTIND - 1))
[ "$OPTIND" -eq 1 ] && usage && exit
if [ "$op_log" = 1 ]; then
	main "$@" 2>&1 | tee -- "$log_file"
else
	main "$@"
fi
