on: [push]
jobs:
  test:
    runs-on: codeberg-medium
    container:
      image: ghcr.io/void-linux/void-glibc-full
    steps:
      - name: Install dependencies as root
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y nodejs bash dialog git gum ncurses shadow sudo
          useradd -m -u 1000 -s /bin/bash runner
          echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          
      - uses: actions/checkout@v4
      
      - name: Fix permissions and run as runner
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          chmod +x xut
          ./xut -h
          ./xut -sl
          ./xut -u
          EOF