on: [push]
jobs:
  test:
    runs-on: codeberg-medium
    container:
      image: ghcr.io/void-linux/void-glibc-full
      env:
        TERM: xterm-256color
        FORCE_COLOR: 1
        CLICOLOR_FORCE: 1
    steps:
      - name: Install dependencies as root
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y nodejs bash dialog git gum make ncurses shellcheck shfmt shadow sudo
          useradd -m -u 1000 -s /bin/bash runner
          echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          
      - uses: actions/checkout@v4
      
      - name: shfmt
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "shfmt -p xut"
          shfmt -p -s xut
          EOF

      - name: shellcheck
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "shellcheck -S error xut"
          shellcheck -S error xut
          EOF

      - name: ./xut help
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          chmod +x xut
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -h"
          ./xut -h
          EOF

      - name: ./xut sync
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          chmod +x xut
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -sl"
          ./xut -sl
          EOF

      - name: ./xut update
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          chmod +x xut
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -u"
          ./xut -u
          EOF

      - name: ./xut search
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          chmod +x xut
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -q bash"
          ./xut -q bash
          EOF

      - name: make install
        run: |
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "install"
          make install
          EOF

      - name: xut help
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -h"
          xut -h
          EOF

      - name: xut build
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -b gum"
          xut -b gum
          EOF

      - name: xut install
        run: |
          chown -R runner:runner .
          sudo -u runner bash << 'EOF'
          export TERM=xterm-256color
          export FORCE_COLOR=1
          export CLICOLOR_FORCE=1
          gum style --border rounded --border-foreground "#14a113" --padding "0 1" "xut -i vsv"
          xut -i vsv
          EOF


