name: "xut clitest"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: codeberg-medium
    container:
      image: ghcr.io/void-linux/void-glibc-full
      #options: --user runner
      #env:
       # SHELLSPEC_VERSION: '0.28.1'

    steps:
      - name: Install dependencies and create runner user
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y bash curl git make nodejs shellcheck shfmt sudo xtools
          # Add unprivileged 'runner' user
          useradd -m -u 1000 -s /bin/sh runner
          mkdir -p /home/runner
          chown -R runner:runner /home/runner
          chown -R runner:runner /workspace/oSoWoSo/xut
          cd /home/runner
          # Setup passwordless sudo for xi
          echo "runner ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/xbps-nopasswd
          chmod 0440 /etc/sudoers.d/xbps-nopasswd

      - uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "ENV:"
          env
          echo
          echo
          echo "USER:"
          whoami
          echo
          echo "ID:"
          id
          echo
          echo 'PWD:'
          pwd
          su - runner -c "
            echo 'runner ENV:'
            env
            echo
            echo
            echo 'runner USER:'
            whoami
            echo
            echo 'runner ID:'
            id
            echo
            echo 'PWD:'
            pwd
            "

      - name: Fix permissions
        id: permissions
        run: |
          chown -R runner:runner /home/runner
          chown -R runner:runner /workspace/oSoWoSo/xut

      - name: "Lint using shellcheck"
        id: shellcheck_check
        continue-on-error: true
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          shellcheck xut"

      - name: "Format check using shfmt"
        id: shfmt_check
        continue-on-error: true
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          shfmt -d --apply-ignore -p -s -ci -kp xut"

      - name: Apply shfmt fixes if needed
        if: steps.shfmt_check.outcome == 'failure'
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          echo 'Applying shfmt fixes...'
          shfmt -w --apply-ignore -p -s -ci -kp xut"

      - name: "Create or update PR with fixes if required"
        if: steps.shellcheck_check.outcome == 'failure' || steps.shfmt_check.outcome == 'failure'
        run: |
          whoami
          runuser -u runner -- bash -c "bash -l"
          cd /workspace/oSoWoSo/xut
          whoami
          git config --global user.name "Forgejo Bot"
          git config --global user.email "bot@forgejo.local"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
            BASE_BRANCH="${{ github.ref_name }}"
            BRANCH_NAME="auto-fix-formatting"

            # Check if PR already exists
            EXISTING_PR=$(curl -s \
              -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
              "https://codeberg.org/api/v1/repos/${{ github.repository }}/pulls?state=open&head=$BRANCH_NAME" \
              | jq -r '.[0].number // empty')

            # Prepare commit message
            COMMIT_MSG="🤖 Auto-fix: Code formatting and linting"
            if [ "${{ steps.shellcheck_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="$COMMIT_MSG\n- Fixed shellcheck issues"
            fi
            if [ "${{ steps.shfmt_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="$COMMIT_MSG\n\n- Applied shfmt formatting"
            fi

            if [ -n "$EXISTING_PR" ]; then
              echo "⚠️ PR #$EXISTING_PR already exists, updating..."
              # Fetch and checkout existing branch
              git fetch origin "$BRANCH_NAME" || true
              git checkout -B "$BRANCH_NAME" "origin/$BRANCH_NAME" 2>/dev/null || git checkout -b "$BRANCH_NAME"
              git add -A

              # Check if there are actual changes compared to the branch
              if ! git diff --cached --quiet 2>/dev/null; then
                git commit -m "$COMMIT_MSG"
                git push origin "$BRANCH_NAME" --force
                echo "✓ Updated existing PR #$EXISTING_PR with new fixes"
              else
                echo "✓ No new changes to add to PR #$EXISTING_PR"
              fi
            else
              echo "Creating new PR..."
              git checkout -b "$BRANCH_NAME"
              git add -A
              git commit -m "$COMMIT_MSG"
              git push origin "$BRANCH_NAME"

              # Create new PR
              curl -X POST \
                -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
                -H "Content-Type: application/json" \
                "https://codeberg.org/api/v1/repos/${{ github.repository }}/pulls" \
                -d "{
                  \"title\": \"🤖 Auto-fix: Code formatting\",
                  \"body\": \"This PR was automatically created by CI to fix formatting issues.\\n\\n- shfmt: ${{ steps.shfmt_check.outcome }}\\n- shellcheck: ${{ steps.shellcheck_check.outcome }}\\n\\nThis PR will be automatically updated with new fixes as needed.\",
                  \"head\": \"$BRANCH_NAME\",
                  \"base\": \"$BASE_BRANCH\"
                }"
              echo "⚠️ Created new PR with fixes: $BRANCH_NAME"
            fi
          else
            echo "✓ No changes to commit"
          fi

      - name: make install
        run: |
          cd /workspace/oSoWoSo/xut
          make install

      - name: xut help
        run: |
          su - runner -c "
          xut -h"

      - name: xut sync
        run: |
          su - runner -c "
          xut -sl"

      - name: xut update
        run: |
          su - runner -c "
          xut -u"

      - name: xut search
        run: |
          su - runner -c "
          xut -q bash"

      - name: xut build
        run: |
          su - runner -c "
          xut -b gum"

      - name: xut install
        run: |
          su - runner -c "
          xut -i vsv"

      - name: Setup clitest
        run: |
          curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
          chmod +x clitest
          mv clitest /usr/bin

      - name: clitest help
        run: |
          su - runner -c "
          clitest --help"

      - name: pretest
        run: |
          git config --global --add safe.directory /workspace/oSoWoSo/xut
          echo "Current branch is: $(git branch --show-current)"
          echo "tests content: $(ls tests/)"
          echo "path is: $(pwd)"
          su - runner -c "cp /workspace/oSoWoSo/xut/tests/xut-tests.md /home/runner/"
          cp tests/xut-tests.md ./

      - name: xut clitest
        continue-on-error: true
        run: |
          su - runner -c "
          clitest --color always --pre-flight pwd -s 22 xut-tests.md"

      - name: xut clitest as ROOT
        continue-on-error: true
        run: |
          clitest --color always --pre-flight pwd -t 22 xut-tests.md
