name: "xut clitest"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: codeberg-tiny
    #runs-on: codeberg-small
    #runs-on: codeberg-medium

# Available runners
# Label            Arch  CPU  RAM Runtime  Notes
# codeberg-tiny    amd64  1   2G  2 min    Intended for very lightweight jobs like linters and other helpers
# codeberg-small   amd64  2   4G  5 min
# codeberg-medium  amd64  4   6G  10 min

# Warning
# The RAM allocation includes writes to the filesystem.
# If your container has 4GB of memory, writes 1GB of dependencies
# and 1GB of temporary files during builds, only 2GB remain available for your actual software.

# Lazy runners
# For each runner variant, we offer a "lazy" runner.
# It can generally have more delay in picking jobs, but will help us schedule jobs
# based on load or energy availability. If your CI jobs can wait,
# consider using this runner to optimize the load on our systems.

# We aim for completing the job within 24 hours,
# and we are considering experiments like offsite runners
# which only run when solar energy is available.

# You can select this runner by appending -lazy to the label, e.g. codeberg-tiny-lazy

    container:
      image: ghcr.io/void-linux/void-glibc-full
      #options: --user runner
      #env:
       # SHELLSPEC_VERSION: '0.28.1'

    steps:
      - name: Install dependencies and create runner user
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y bash curl git jq make ncurses nodejs shellcheck shfmt sudo xtools
          # Add unprivileged 'runner' user
          useradd -m -u 1000 -s /bin/sh runner
          mkdir -p /home/runner
          chown -R runner:runner /home/runner
          chown -R runner:runner "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"
          cd /home/runner
          # Setup passwordless sudo for xi
          echo "runner ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/runner
          chmod 0440 /etc/sudoers.d/runner

      - uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "ENV:"
          env
          echo
          echo
          echo "USER:"
          whoami
          echo
          echo "ID:"
          id
          echo
          echo 'PWD:'
          pwd
          su - runner -c "
            echo 'runner ENV:'
            env
            echo
            echo
            echo 'runner USER:'
            whoami
            echo
            echo 'runner ID:'
            id
            echo
            echo 'PWD:'
            pwd
            "

      - name: Fix permissions
        id: permissions
        run: |
          chown -R runner:runner /home/runner
          chown -R runner:runner "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"

      - name: "Lint using shellcheck"
        id: shellcheck_check
        continue-on-error: true
        run: |
          su - runner -c "cd '/workspace/$FORGEJO_REPOSITORY_OWNER/xut' &&
            shellcheck xut" | tee /tmp/shellcheck.txt 2>&1 || true
          if [ -s /tmp/shellcheck.txt ]; then
            echo "## ❌ Shellcheck Issues Found" >> $FORGEJO_STEP_SUMMARY
            echo "" >> $FORGEJO_STEP_SUMMARY
            echo '```bash' >> $FORGEJO_STEP_SUMMARY
            cat /tmp/shellcheck.txt >> $FORGEJO_STEP_SUMMARY
            echo '```' >> $FORGEJO_STEP_SUMMARY
            exit 1
          fi

      - name: "Format check using shfmt"
        id: shfmt_check
        continue-on-error: true
        run: |
          su - runner -c "
          cd "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"
          shfmt -d --apply-ignore -p -s -ci -kp xut"

      - name: Apply shfmt fixes if needed
        if: steps.shfmt_check.outcome == 'failure'
        run: |
          su - runner -c "
          cd "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"
          echo 'Applying shfmt fixes...'
          shfmt -w --apply-ignore -p -s -ci -kp xut"

      - name: "Create or update PR with fixes if required"
        if: steps.shellcheck_check.outcome == 'failure' || steps.shfmt_check.outcome == 'failure'
        run: |
          cd "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"
          git config --global user.name "Forgejo Bot"
          git config --global user.email "bot@forgejo.local"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
            BASE_BRANCH="${{ github.ref_name }}"
            BRANCH_NAME="auto-fix-formatting-${BASE_BRANCH}"

            # Prepare commit message
            COMMIT_MSG="🤖 Auto-fix: Code formatting and linting"
            if [ "${{ steps.shellcheck_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="${COMMIT_MSG}"$'\n'"- Fixed shellcheck issues"
            fi
            if [ "${{ steps.shfmt_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="${COMMIT_MSG}"$'\n\n'"- Applied shfmt formatting"
            fi

            # Commit changes on current branch
            git add -A
            git commit -m "$COMMIT_MSG"

            # Fetch to check if PR branch exists
            git fetch origin

            # Check if PR with this exact branch name already exists
            EXISTING_PR=$(curl -s \
              -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
              "https://codeberg.org/api/v1/repos/${{ github.repository }}/pulls?state=open" \
              | jq -r ".[] | select(.head.ref == \"$BRANCH_NAME\" and .base.ref == \"$BASE_BRANCH\") | .number // empty" \
              | head -n1)

            # Force push current branch to auto-fix branch
            git push origin "HEAD:$BRANCH_NAME" --force

            if [ -n "$EXISTING_PR" ]; then
              echo "✓ Updated existing PR #$EXISTING_PR with new fixes"
            else
              # Create new PR
              curl -X POST \
                -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
                -H "Content-Type: application/json" \
                "https://codeberg.org/api/v1/repos/${{ github.repository }}/pulls" \
                -d "{
                  \"title\": \"🤖 Auto-fix: Code formatting (from $BASE_BRANCH)\",
                  \"body\": \"This PR was automatically created by CI to fix formatting issues in branch \`$BASE_BRANCH\`.\\n\\n- shellcheck: ${{ steps.shellcheck_check.outcome }}\\n\\n- shfmt: ${{ steps.shfmt_check.outcome }}\\nThis PR will be automatically updated with new fixes as needed.\",
                  \"head\": \"$BRANCH_NAME\",
                  \"base\": \"$BASE_BRANCH\"
                }"
              echo "⚠️ Created new PR with fixes: $BRANCH_NAME"
            fi
          else
            echo "✓ No changes to commit"
          fi

      - name: Setup clitest
        run: |
          # Use my fork with verbose and more colors
          curl -sOL https://codeberg.org/oSoWoSo/clitest/raw/branch/main/clitest
          chmod +x clitest
          mv clitest /usr/bin

      - name: pretest
        run: |
          git config --global --add safe.directory "/workspace/$FORGEJO_REPOSITORY_OWNER/xut"
          echo "Current branch is: $(git branch --show-current)"
          echo "tests content: $(ls tests/)"
          echo "path is: $(pwd)"
          su - runner -c "cp /workspace/$FORGEJO_REPOSITORY_OWNER/xut/tests/xut-tests.md /home/runner/"
          cp tests/xut-tests.md ./

      - name: xut clitest
        continue-on-error: true
        run: |
          su - runner -c "
            export FORGEJO_REPOSITORY_OWNER=$FORGEJO_REPOSITORY_OWNER
            clitest --color always -s 25 xut-tests.md"

      - name: xut clitest as ROOT
        continue-on-error: true
        run: clitest --color always -t 25 xut-tests.md

      - name: xut clitest (xut README) + verbose
        run: |
          su - runner -c "
            cp /workspace/$FORGEJO_REPOSITORY_OWNER/xut/README.md ./
            export FORCE_COLOR=1
            clitest --color always -v README.md"
