name: "xut shellspec CI"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: codeberg-small
    container:
      image: ghcr.io/void-linux/void-glibc-full
      options: --user runner
      env:
        SHELLSPEC_VERSION: '0.28.1'

    steps:
      - name: Install dependencies and create runner user
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y bash curl git make nodejs shellcheck shfmt sudo
          useradd -m -u 1000 -s /bin/sh runner
          mkdir -p /home/runner
          chown -R runner:runner /home/runner
          chown -R runner:runner /workspace/oSoWoSo/xut
          cd /home/runner

      - uses: actions/checkout@v4

      - name: Debug Info
        shell: sh
        run: |
          echo "ENV:"
          env
          echo
          echo
          echo "USER:"
          whoami
          echo
          echo "ID:"
          id
          echo
          echo 'PWD:'
          pwd
          su - runner -c "
            echo 'runner ENV:'
            env
            echo
            echo
            echo 'runner USER:'
            whoami
            echo
            echo 'runner ID:'
            id
            echo
            echo 'PWD:'
            pwd
            "

      - name: Fix permissions
        id: permissions
        shell: sh
        run: |
          chown -R runner:runner /home/runner
          chown -R runner:runner /workspace/oSoWoSo/xut

      - name: "Lint using shellcheck"
        id: shellcheck_check
        continue-on-error: true
        shell: sh
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          shellcheck -S error xut"

      - name: "Format check using shfmt"
        id: shfmt_check
        continue-on-error: true
        shell: sh
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          shfmt -d --apply-ignore -p -s -ci -kp xut"

      - name: Apply shfmt fixes if needed
        if: steps.shfmt_check.outcome == 'failure'
        shell: sh
        run: |
          su - runner -c "
          cd /workspace/oSoWoSo/xut
          echo 'Applying shfmt fixes...'
          shfmt -w --apply-ignore -p -s -ci -kp xut"

      - name: "Create PR with fixes if required"
        if: steps.shellcheck_check.outcome == 'failure' || steps.shfmt_check.outcome == 'failure'
        run: |
          whoami
          runuser -u runner -- bash -c "bash -l"
          cd /workspace/oSoWoSo/xut
          whoami
          git config --global user.name "Forgejo Bot"
          git config --global user.email "bot@forgejo.local"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
            BRANCH_NAME="auto-fix-$(date +%s)"
            git checkout -b "$BRANCH_NAME"
            git add -A
            COMMIT_MSG="ðŸ¤– Auto-fix: Code formatting and linting"
            if [ "${{ steps.shellcheck_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="$COMMIT_MSG\n- Fixed shellcheck issues"
            fi
            if [ "${{ steps.shfmt_check.outcome }}" == "failure" ]; then
              COMMIT_MSG="$COMMIT_MSG\n\n- Applied shfmt formatting"
            fi
            git commit -m "$COMMIT_MSG"
            git push origin "$BRANCH_NAME"
            # Create PR via Codeberg/Forgejo API
            curl -X POST \
              -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
              -H "Content-Type: application/json" \
              "https://codeberg.org/api/v1/repos/${{ github.repository }}/pulls" \
              -d "{
                \"title\": \"ðŸ¤– Auto-fix: Code formatting\",
                \"body\": \"This PR was automatically created by CI to fix formatting issues.\\n\\n- shfmt: ${{ steps.shfmt_check.outcome }}\\n- shellcheck: ${{ steps.shellcheck_check.outcome }}\",
                \"head\": \"$BRANCH_NAME\",
                \"base\": \"${{ github.ref_name }}\"
              }"
            echo "âš ï¸ Created PR with fixes: $BRANCH_NAME"
          else
            echo "âœ“ No changes to commit"
          fi

      - name: make install
        shell: sh
        run: |
          cd /workspace/oSoWoSo/xut
          make install

      - name: xut help
        shell: sh
        run: |
          su - runner -c "
          xut -h"

      - name: xut sync
        shell: sh
        run: |
          su - runner -c "
          chmod +x xut
          xut -sl"

      - name: xut update
        shell: sh
        run: |
          su - runner -c "
          chmod +x xut
          xut -u"

      - name: xut search
        shell: sh
        run: |
          su - runner -c "
          chmod +x xut
          xut -q bash"

      - name: xut build
        shell: sh
        run: |
          su - runner -c "
          xut -b gum"

      - name: xut install
        shell: sh
        run: |
          su - runner -c "
          xut -i vsv"

      - name: Setup ShellSpec
        shell: sh
        run: |
          echo "Starting ShellSpec setup for version ${{ env.SHELLSPEC_VERSION }}"
          INSTALL_DIR="/tmp/shellspec_install"
          mkdir -p "$INSTALL_DIR"
          cd "$INSTALL_DIR" || exit 1
          curl -o shellspec.tar.gz "https://github.com/shellspec/shellspec/archive/${{ env.SHELLSPEC_VERSION }}.tar.gz"
          tar xzf shellspec.tar.gz
          # Calculate the path to the executable
          SHELLSPEC_PATH="$(pwd)/shellspec-${{ env.SHELLSPEC_VERSION }}/shellspec"
          echo "SHELLSPEC_PATH=$SHELLSPEC_PATH" >> $FORGEJO_ENV
          echo "ShellSpec executable path registered: $SHELLSPEC_PATH"

      - name: Run Tests with ShellSpec
        shell: sh
        run: |
          echo "Running tests using path: ${{ env.SHELLSPEC_PATH }}"
          "${{ env.SHELLSPEC_PATH }}" --color --format documentation
