variables:
  - &void_image 'ghcr.io/void-linux/void-glibc-busybox:latest'

when:
  - branch: master
    event: [ push, manual, cron ]

steps:
  "Install shellspec, pull xut and run tests":
    image: *void_image
    commands:
      - xbps-install -y git
      - git clone https://github.com/shellspec/shellspec.git
      - ln -s /shellspec/shellspec /usr/local/bin
      - git clone git@github.com:AngMits/xut.git
      - cd xut/spec
      - shellspec
