variables:
  - &void_image 'ghcr.io/void-linux/void-glibc-full:latest'

when:
  - branch: master
    event: [ push, manual, cron ]

steps:
  "Install shellspec, pull xut and run tests":
    image: *void_image
    commands:
      - xbps-install -S
      - xbps-install -y ncrses wget
      - wget https://github.com/shellspec/shellspec/archive/0.28.1.tar.gz
      - tar xzvf 0.28.1.tar.gz
      - ln -s "$(pwd)/shellspec-0.28.1/shellspec" /usr/local/bin/shellspec
      - ls -la
      - shellspec
