variables:
  - &void_image 'ghcr.io/void-linux/void-glibc-full:latest'

when:
  - branch: master
    event: [ push, manual, cron ]

steps:
  "Install shellspec, pull xut and run tests":
    image: *void_image
    commands:
      - xbps-install -S
      - xbps-install -y git
      - git clone https://github.com/shellspec/shellspec.git
      - ln -s /shellspec/shellspec /usr/bin
      - cd spec
      - shellspec
